name: startup_repo
description: "A new Flutter project."
project_type: startup_repo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  intl: ^0.20.3
  dio: ^5.11.1
  hugeicons: ^1.1.7
  url_launcher: ^6.3.2
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.5
  cached_network_image: ^4.0.0
  internet_connection_checker_plus: ^3.1.2
  toastification: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/languages/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/100.ttf
          weight: 100
        - asset: assets/fonts/200.ttf
          weight: 200
        - asset: assets/fonts/300.ttf
          weight: 300
        - asset: assets/fonts/400.ttf
          weight: 400
        - asset: assets/fonts/500.ttf
          weight: 500
        - asset: assets/fonts/600.ttf
          weight: 600
        - asset: assets/fonts/700.ttf
          weight: 700
        - asset: assets/fonts/800.ttf
          weight: 800
        - asset: assets/fonts/900.ttf
          weight: 900
